version: '3'
services:
  client:
    build: ./client
    container_name: client
    ports:
    - '4200:4200'
    volumes:
      - ./client:/usr/src/app
    depends_on: 
      - api
    networks:
      - my-net
  api:
    build: ./api
    container_name: api
    ports:
    - '3000:3000'
    volumes:
      - ./api:/usr/src/app
    depends_on: 
      - mongodb
    links:
        - mongodb
    networks:
      - my-net
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
        MONGO_ROOT_USERNAME: ll8U1hvnjki19NPMwyzIQGueVb8qAAOY
        MONGO_ROOT_PASSWORD: SVvHl14jYqfnQScRaRtsiiYdZ453jV7i
        MONGO_DATABASE: botlegger
    ports:
        - 27017:27017
    volumes:
        - ./mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - my-net

networks:
  my-net:
    driver: bridge